### PR TITLE
change icon to icon with white background

### LINKED ISSUE #81: Corrigir icon da aplicação

### PR DESCRIPTION
**Pull request by AntonioNevess**
Changed icon to white background so all devices have an icon with white background.

Close #81

### CODE REVIEW

**Review by Marcel0Mat0s — APPROVED** [review]
LGTM!

**Comment by JKZ02** [comment]
I know I'm not assigned to this PR, but please try not to commit anything in the /platforms folder as it only makes it harder for the reviewers to verify everything is working correctly, and can also cause uncalled-for conflicts which is the case in this commit.

**Review by AlixAPCarmo — APPROVED** [review]
LGTM!

**Review by anagracio — APPROVED** [review]
Tested on 3 mobile devices. Looks good to me!

**Review by anagracio — APPROVED** [review]

**Pull request merged**
