### PR TITLE
Add markers to map

### PR DESCRIPTION
**Pull request by AlixAPCarmo**
Closes issue #8

### CODE REVIEW

**Review by dgraca — APPROVED** [review]
Be carefull when installing plugins you don't know what they do.
If not using, remove them. They were crashing all application

**Comment by JKZ02** [comment]
Seems good, conflicting files won't have any effect on our work.

**Review by JKZ02 — APPROVED** [review]
Seems good, conflicting files won't have any effect on our work.

**Review by dgraca — APPROVED** [review]
LGTM

**Pull request merged**
