### PR TITLE
Iteractive points description

### LINKED ISSUE #47: Como utilizador quero ser capaz de visualizar todos os elementos presentes em cada edificio com mais detalhe

### PR DESCRIPTION
**Pull request by anagracio**
Closes #47

### CODE REVIEW

**Comment by dgraca** [comment]
👀

**Review by JKZ02 — APPROVED** [review]
Working on android, seems good to me.

**Review by AlixAPCarmo — APPROVED** [review]
Looks good to me.

**Review by AntonioNevess — APPROVED** [review]
Tested and it works!

**Pull request merged**
