### PR TITLE
Images size and enlarge

### LINKED ISSUE #87: Conseguir ampliar a imagem dos pontos interactivos

### LINKED ISSUE #93: Redimensionar as imagens para ficarem todas com o mesmo tamanho

### LINKED ISSUE #101: Resolver Bug de algumas imagens não aparecerem nos detalhes dos pontos

### PR DESCRIPTION
**Pull request by anagracio**
- Changed the interactive point images to a dimension of 1024x1024;
- Added a new page: By clicking an image in the carousel, we can see a page with only the selected image.
- [FIX] Images not loading dues to bad file formatting are now loading correctly

Closes #87, Closes #93, Closes #101

### CODE REVIEW

**Review by dgraca — APPROVED** [review]
LGTM! Tested on Redmi Note 10 Pro.

We could add a button to go back to the interactive point also, but with lack of time everything goes now.

image

**Review by dgraca — APPROVED** [review]
LGTM! 🚀 Tested on Redmi Note 10 Pro

Solved the images issue in this branch. LET's GO

bug-fix-fixing-bugs-in-your-code

**Review by JKZ02 — APPROVED** [review]
Seems good, nice work!

**Review by Marcel0Mat0s — APPROVED** [review]
LGTM!

**Pull request merged**
