### PR TITLE
bug fixed

### LINKED ISSUE #89: Resolver Bug de abrir descrição do marker errado

### PR DESCRIPTION
**Pull request by Marcel0Mat0s**
Bug where the worng markers description appeared fixed.
Close #89

### CODE REVIEW

**Comment by dgraca** [comment]
First of all: the title **BUG FIX** doesn't tell what the bug that was fixed.
Second: what the actual 🦆 is that description?
Third: now that I made my rant, im going to review the code. I'll let you know my feedback

**Review by dgraca — CHANGES_REQUESTED** [review]
This function does not receive an object as a parameter. It receives an ID. You could call it objId and define a __const ID = objId - 1;__, which is fine. This way you should change the description of the function.

image


The second option is just to do as below:
image

Either way, good work on finding the bug origin. Keep up the good work 🚀 

The third option is to pass the element to the function and get the indexOf that element from the data array.

I would recommend you to just do the second option as it is the one that requires less work and also looks clean

**Comment by Marcel0Mat0s** [comment]
Did as asked, ty Dionel!

**Review by dgraca — APPROVED** [review]
LGTM! 🚀

**Review by anagracio — APPROVED** [review]
Tested! LGTM!

**Pull request merged**
