### PR TITLE
Show itineraries

### LINKED ISSUE #49: Como utilizador quero ser capaz de visualizar um itenerário escolhido por mim

### PR DESCRIPTION
**Pull request by Marcel0Mat0s**
The itineraries are showing on the map in green and yellow like requested.
Closes #49

### CODE REVIEW

**Review by dgraca — CHANGES_REQUESTED** [review]
Everything looks great!

Great work overall. Yet, as we discussed with Professor Paulo, you should implement a functionality that centers the map in the iteneraries when you click on its button.

Let's go! 🚀

**Review by dgraca — APPROVED** [review]
LGTM! 🚀

**Review by AlixAPCarmo — APPROVED** [review]
Good Job here! Works fine for me.

**Review by JKZ02 — APPROVED** [review]
Looking good, tested on android, no apparent issues found.
Also didn't find any issues with the code.
Good job!

**Pull request merged**
